
APP_UPT_STATE_SUCC = 2
APP_UPT_STATE_IDLE = 0
APP_UPT_STATE_WORKING = 1
APP_UPT_STATE_FAILED = -1
WIFI_CONFIG = 10
WIFI_CONNECTING = 2
WIFI_IDLE = 0
WIFI_FAILED = -1
WIFI_SUCC = 1
TIME_SYNCING = 2
TIME_SUCC = 1
TIME_FAILED = -1
FS_MSG_NEW_DISK = 1
FS_MSG_CORRUPT = 2
LED1 = 32
LED2 = 33
